name: "ownyourcode"
description: "Identify orphan files missing codeowners"
author: "Girges Scandar"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "users"
  color: "orange"

inputs:
  fail-on-missing-codeowners:
    description: "Fail CI if there are files without owners"
    default: "true"
    required: false
  github_token:
    description: "Github Token"
    required: true
  pr_number:
    description: "Scan only the files modified in the PR"
    required: false
  branch:
    description: "Scan all files in the specified branch"
    required: false
  codeowners_path:
    description: "Path to the codeowners file"
    default: "CODEOWNERS"
    required: false

outputs:
  total_orphan_files:
    description: "Total number of orphaned files"
    value: ${{ steps.codeowners.outputs.total_orphan_files }}
  total_scanned_files:
    description: "Total files"
    value: ${{ steps.codeowners.outputs.total_scanned_files }}
  failed:
    description: "If the action failed"
    value: ${{ steps.codeowners.outputs.failed }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.action_repository }}

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: npm

    - name: Install Dependencies
      shell: bash
      id: npm-ci
      run: npm ci

    - name: Check Codeowners
      shell: bash
      run: node ./dist/index.js
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_CODEOWNERS_PATH: ${{ inputs.codeowners_path }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        INPUT_FAIL_ON_MISSING_CODEOWNERS:
          ${{ inputs.fail-on-missing-codeowners }}
        INPUT_BRANCH: ${{ inputs.branch }}
