name: "ownyourcode"
description: "Identify orphan files missing codeowners"
author: "Girges Scandar"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "users"
  color: "orange"

inputs:
  fail-on-missing-codeowners:
    description: "Fail CI if there are files without owners"
    default: "true"
    required: false
  github_token:
    description: "Github Token"
    required: true
  pr-number:
    description: "Scan only the files modified in the PR"
    required: false
  branch:
    description: "Scan all files in the specified branch"
    required: false
  codeowners_path:
    description: "Path to the codeowners file"
    default: "CODEOWNERS"
    required: false
  codeartifact-auth-token:
    description: "Token for the registry"
    required: true
# outputs:
#   total_orphan_files:
#     description: "Total number of orphaned files"
#     value: ${{ steps.codeowners.outputs.total_orphan_files }}
#   total_scanned_files:
#     description: "Total files"
#     value: ${{ steps.codeowners.outputs.total_scanned_files }}
#   failed:
#     description: "If the action failed"
#     value: ${{ steps.codeowners.outputs.failed }}

runs:
  using: node20
  main: dist/index.js
