name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
permissions:
  id-token: write
  contents: read
  pull-requests: write # we need this to write comments in PRs

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action-pr:
    if: github.event_name == 'pull_request'
    name: Test action - PR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write # we need this to write comments in PRs

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.total_orphan_files }}"
          echo "${{ steps.test-action.outputs.total_scanned_files }}"
          echo "${{ steps.test-action.outputs.failed }}"

  test-action-branch:
    name: Test action - Branch
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write # we need this to write comments in PRs

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main" # use ${{ github.ref_name }} when using this on a real branch
          fail_on_missing_codeowners: false

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.total_orphan_files }}"
          echo "${{ steps.test-action.outputs.total_scanned_files }}"
          echo "${{ steps.test-action.outputs.failed }}"
